//! A password-sealed 32-byte key at rest, in one of two mutually exclusive shapes.
//!
//! Both shapes bind their own Argon2id parameters: they are stored in the
//! record, fed to the KDF, and covered as associated data, so a
//! tampered-parameter record fails authentication and a reader always knows
//! exactly what to run. Parameter ceilings are enforced before any KDF work,
//! so a tampered record cannot drive a pathological memory allocation before
//! the forgery is even detectable. The two shapes are distinguished by an
//! explicit version byte (never by incidental length alone) and are
//! independently exact-length records, so one shape's record can never be
//! misread as the other's: [`open_key32_with_password`] rejects anything
//! that is not exactly a stored-salt record, and
//! [`open_key32_with_password_and_caller_salt`] rejects anything that is not
//! exactly a caller-salt record.
//!
//! # Stored-salt shape (version `0x01`, 117 bytes)
//!
//! Layout: version `0x01` | salt (32) | memory cost KiB (4 LE) | iterations (4
//! LE) | parallelism (4 LE) | nonce (24) | XChaCha20-Poly1305 ciphertext over
//! the 32-byte key with its 16-byte tag (48). Associated data is the 45 bytes
//! preceding the nonce, exactly as stored. The salt is generated by this
//! module and stored in the record.
//!
//! # Caller-salt shape (version `0x02`, 85 bytes)
//!
//! Layout: version `0x02` | memory cost KiB (4 LE) | iterations (4 LE) |
//! parallelism (4 LE) | nonce (24) | XChaCha20-Poly1305 ciphertext over the
//! 32-byte key with its 16-byte tag (48). Associated data is the 13 bytes
//! preceding the nonce, exactly as stored. The salt is never generated or
//! stored by this module; the caller supplies exactly the same 32-byte secret
//! salt to both [`seal_key32_with_password_and_caller_salt`] and
//! [`open_key32_with_password_and_caller_salt`], out of band from the record.
//! This shape exists for cases where the salt is itself secret key material
//! held elsewhere (for example, a second independently held factor), so it
//! is accepted and returned only as [`Key32`]: never as the public,
//! non-zeroizing [`PasswordKdfSalt`].
//!
//! Randomness (salt, where generated, and nonce) is caller-injected so
//! sans-IO consumers can drive sealing without this crate reaching for an
//! ambient random source.

use zeroize::Zeroize;

use crate::crypto::error::Error;
use crate::crypto::{
    Key32, PASSWORD_KDF_MAX_PARALLELISM, PASSWORD_KDF_SALT_SIZE, PasswordKdfParams,
    PasswordKdfSalt, SecretBytes, XCHACHA20_POLY1305_NONCE_SIZE, XCHACHA20_POLY1305_TAG_SIZE,
    decrypt_xchacha20_poly1305, derive_argon2id_key32_from_password_bytes,
    encrypt_xchacha20_poly1305,
};

/// Record version written and accepted by [`seal_key32_with_password`] and
/// [`open_key32_with_password`] (the stored-salt shape).
pub const PASSWORD_SEALED_KEY32_VERSION: u8 = 1;

/// Record version written and accepted by
/// [`seal_key32_with_password_and_caller_salt`] and
/// [`open_key32_with_password_and_caller_salt`] (the caller-salt shape).
pub const PASSWORD_SEALED_KEY32_CALLER_SALT_VERSION: u8 = 2;

/// Exact size, in bytes, of a stored-salt password-sealed key record.
pub const PASSWORD_SEALED_KEY32_RECORD_SIZE: usize =
    HEADER_SIZE + XCHACHA20_POLY1305_NONCE_SIZE + 32 + XCHACHA20_POLY1305_TAG_SIZE;

/// Exact size, in bytes, of a caller-salt password-sealed key record.
pub const PASSWORD_SEALED_KEY32_CALLER_SALT_RECORD_SIZE: usize =
    CALLER_SALT_HEADER_SIZE + XCHACHA20_POLY1305_NONCE_SIZE + 32 + XCHACHA20_POLY1305_TAG_SIZE;

/// Maximum accepted Argon2id memory cost on read, KiB (4 GiB).
pub const PASSWORD_SEALED_KEY32_MAX_MEMORY_COST_KIB: u32 = 4 * 1024 * 1024;

/// Maximum accepted Argon2id iteration count on read.
pub const PASSWORD_SEALED_KEY32_MAX_ITERATIONS: u32 = 65_536;

const KDF_PARAM_BYTES_SIZE: usize = 12;
const HEADER_SIZE: usize = 1 + PASSWORD_KDF_SALT_SIZE + KDF_PARAM_BYTES_SIZE;
const NONCE_OFFSET: usize = HEADER_SIZE;
const CIPHERTEXT_OFFSET: usize = NONCE_OFFSET + XCHACHA20_POLY1305_NONCE_SIZE;

const CALLER_SALT_HEADER_SIZE: usize = 1 + KDF_PARAM_BYTES_SIZE;
const CALLER_SALT_NONCE_OFFSET: usize = CALLER_SALT_HEADER_SIZE;
const CALLER_SALT_CIPHERTEXT_OFFSET: usize =
    CALLER_SALT_NONCE_OFFSET + XCHACHA20_POLY1305_NONCE_SIZE;

/// Seals a 32-byte key under a password with a self-generated, stored salt
/// and caller-injected randomness.
///
/// `params` are validated by [`PasswordKdfParams`]'s own floor and ceiling;
/// callers with stricter floors enforce them before calling. `fill_random`
/// must fill its argument with cryptographically secure random bytes and may
/// report failure with [`Error::InjectedRandomFillFailed`].
pub fn seal_key32_with_password<K>(
    key: &Key32,
    password: &SecretBytes<K>,
    params: PasswordKdfParams,
    mut fill_random: impl FnMut(&mut [u8]) -> Result<(), Error>,
) -> Result<Vec<u8>, Error> {
    let mut salt_bytes = [0_u8; PASSWORD_KDF_SALT_SIZE];
    fill_random(&mut salt_bytes)?;
    let salt = PasswordKdfSalt::from_bytes(&salt_bytes)?;

    let mut header = [0_u8; HEADER_SIZE];
    header[0] = PASSWORD_SEALED_KEY32_VERSION;
    header[1..1 + PASSWORD_KDF_SALT_SIZE].copy_from_slice(&salt_bytes);
    write_kdf_param_bytes(
        (&mut header[1 + PASSWORD_KDF_SALT_SIZE..HEADER_SIZE])
            .try_into()
            .expect("12"),
        params,
    );

    let mut nonce = [0_u8; XCHACHA20_POLY1305_NONCE_SIZE];
    fill_random(&mut nonce)?;

    let kek = derive_argon2id_key32_from_password_bytes(password, salt.as_bytes(), params)?;
    let ciphertext = encrypt_xchacha20_poly1305(&kek, &nonce, &header, key.expose_secret())
        .map_err(Error::from)?;

    let mut record = Vec::with_capacity(PASSWORD_SEALED_KEY32_RECORD_SIZE);
    record.extend_from_slice(&header);
    record.extend_from_slice(&nonce);
    record.extend_from_slice(&ciphertext);
    debug_assert_eq!(record.len(), PASSWORD_SEALED_KEY32_RECORD_SIZE);
    salt_bytes.zeroize();
    Ok(record)
}

/// Reads a stored-salt record's Argon2id parameters without running the KDF,
/// so callers can enforce their own stricter floors before paying for a KDF
/// pass.
pub fn read_password_sealed_key32_params(record: &[u8]) -> Result<PasswordKdfParams, Error> {
    let header = parse_header(record)?;
    Ok(header.params)
}

/// Opens a record sealed by [`seal_key32_with_password`].
///
/// Parameters outside the floor/ceiling are rejected before any KDF work as
/// their own outcomes; a wrong password and a tampered record are
/// indistinguishable by design (both fail the tag). A record sealed by
/// [`seal_key32_with_password_and_caller_salt`] is always rejected here: its
/// length and version byte never match this shape.
pub fn open_key32_with_password<K>(
    record: &[u8],
    password: &SecretBytes<K>,
) -> Result<Key32, Error> {
    let header = parse_header(record)?;
    let nonce: &[u8; XCHACHA20_POLY1305_NONCE_SIZE] = record[NONCE_OFFSET..CIPHERTEXT_OFFSET]
        .try_into()
        .map_err(|_| Error::DecryptionFailed)?;
    let ciphertext = &record[CIPHERTEXT_OFFSET..];

    let kek =
        derive_argon2id_key32_from_password_bytes(password, header.salt.as_bytes(), header.params)?;
    let mut plaintext = decrypt_xchacha20_poly1305(&kek, nonce, &record[..HEADER_SIZE], ciphertext)
        .map_err(Error::from)?;
    let key = Key32::try_from(plaintext.as_slice());
    plaintext.zeroize();
    key
}

/// Seals a 32-byte key under a password and a caller-supplied salt.
///
/// Unlike [`seal_key32_with_password`], `caller_salt` is never generated or
/// stored by this module: the caller must supply the exact same salt back to
/// [`open_key32_with_password_and_caller_salt`], out of band from the
/// returned record. This is for cases where the salt is itself secret key
/// material held elsewhere, so it is a [`Key32`] rather than a
/// [`PasswordKdfSalt`], keeping it inside a zeroizing secret container for
/// its entire lifetime in this crate.
///
/// `params` are validated by [`PasswordKdfParams`]'s own floor and ceiling;
/// callers with stricter floors enforce them before calling. `fill_random`
/// must fill its argument with cryptographically secure random bytes and may
/// report failure with [`Error::InjectedRandomFillFailed`].
pub fn seal_key32_with_password_and_caller_salt<K>(
    key: &Key32,
    password: &SecretBytes<K>,
    caller_salt: &Key32,
    params: PasswordKdfParams,
    mut fill_random: impl FnMut(&mut [u8]) -> Result<(), Error>,
) -> Result<Vec<u8>, Error> {
    let mut header = [0_u8; CALLER_SALT_HEADER_SIZE];
    header[0] = PASSWORD_SEALED_KEY32_CALLER_SALT_VERSION;
    write_kdf_param_bytes(
        (&mut header[1..CALLER_SALT_HEADER_SIZE])
            .try_into()
            .expect("12"),
        params,
    );

    let mut nonce = [0_u8; XCHACHA20_POLY1305_NONCE_SIZE];
    fill_random(&mut nonce)?;

    let kek =
        derive_argon2id_key32_from_password_bytes(password, caller_salt.expose_secret(), params)?;
    let ciphertext = encrypt_xchacha20_poly1305(&kek, &nonce, &header, key.expose_secret())
        .map_err(Error::from)?;

    let mut record = Vec::with_capacity(PASSWORD_SEALED_KEY32_CALLER_SALT_RECORD_SIZE);
    record.extend_from_slice(&header);
    record.extend_from_slice(&nonce);
    record.extend_from_slice(&ciphertext);
    debug_assert_eq!(record.len(), PASSWORD_SEALED_KEY32_CALLER_SALT_RECORD_SIZE);
    Ok(record)
}

/// Reads a caller-salt record's Argon2id parameters without running the KDF
/// and without the caller's salt, so callers can enforce their own stricter
/// floors before paying for a KDF pass.
pub fn read_password_sealed_key32_caller_salt_params(
    record: &[u8],
) -> Result<PasswordKdfParams, Error> {
    let header = parse_caller_salt_header(record)?;
    Ok(header.params)
}

/// Opens a record sealed by [`seal_key32_with_password_and_caller_salt`].
///
/// `caller_salt` must be the exact same [`Key32`] supplied when sealing.
/// Parameters outside the floor/ceiling are rejected before any KDF work as
/// their own outcomes; a wrong password, a wrong salt, and a tampered record
/// are indistinguishable by design (all fail the tag). A record sealed by
/// [`seal_key32_with_password`] is always rejected here: its length and
/// version byte never match this shape.
pub fn open_key32_with_password_and_caller_salt<K>(
    record: &[u8],
    password: &SecretBytes<K>,
    caller_salt: &Key32,
) -> Result<Key32, Error> {
    let header = parse_caller_salt_header(record)?;
    let nonce: &[u8; XCHACHA20_POLY1305_NONCE_SIZE] = record
        [CALLER_SALT_NONCE_OFFSET..CALLER_SALT_CIPHERTEXT_OFFSET]
        .try_into()
        .map_err(|_| Error::DecryptionFailed)?;
    let ciphertext = &record[CALLER_SALT_CIPHERTEXT_OFFSET..];

    let kek = derive_argon2id_key32_from_password_bytes(
        password,
        caller_salt.expose_secret(),
        header.params,
    )?;
    let mut plaintext =
        decrypt_xchacha20_poly1305(&kek, nonce, &record[..CALLER_SALT_HEADER_SIZE], ciphertext)
            .map_err(Error::from)?;
    let key = Key32::try_from(plaintext.as_slice());
    plaintext.zeroize();
    key
}

struct ParsedHeader {
    salt: PasswordKdfSalt,
    params: PasswordKdfParams,
}

struct ParsedCallerSaltHeader {
    params: PasswordKdfParams,
}

fn parse_header(record: &[u8]) -> Result<ParsedHeader, Error> {
    if record.len() != PASSWORD_SEALED_KEY32_RECORD_SIZE {
        return Err(Error::InvalidPasswordSealedKeyLength {
            actual: record.len(),
            want: PASSWORD_SEALED_KEY32_RECORD_SIZE,
        });
    }
    if record[0] != PASSWORD_SEALED_KEY32_VERSION {
        return Err(Error::UnsupportedPasswordSealedKeyVersion { version: record[0] });
    }
    let salt = PasswordKdfSalt::from_bytes(&record[1..1 + PASSWORD_KDF_SALT_SIZE])?;
    let params = read_and_validate_kdf_param_bytes(
        record[1 + PASSWORD_KDF_SALT_SIZE..HEADER_SIZE]
            .try_into()
            .expect("12"),
    )?;
    Ok(ParsedHeader { salt, params })
}

fn parse_caller_salt_header(record: &[u8]) -> Result<ParsedCallerSaltHeader, Error> {
    if record.len() != PASSWORD_SEALED_KEY32_CALLER_SALT_RECORD_SIZE {
        return Err(Error::InvalidPasswordSealedKeyLength {
            actual: record.len(),
            want: PASSWORD_SEALED_KEY32_CALLER_SALT_RECORD_SIZE,
        });
    }
    if record[0] != PASSWORD_SEALED_KEY32_CALLER_SALT_VERSION {
        return Err(Error::UnsupportedPasswordSealedKeyVersion { version: record[0] });
    }
    let params = read_and_validate_kdf_param_bytes(
        record[1..CALLER_SALT_HEADER_SIZE].try_into().expect("12"),
    )?;
    Ok(ParsedCallerSaltHeader { params })
}

fn write_kdf_param_bytes(bytes: &mut [u8; KDF_PARAM_BYTES_SIZE], params: PasswordKdfParams) {
    bytes[0..4].copy_from_slice(&params.memory_cost_kib().to_le_bytes());
    bytes[4..8].copy_from_slice(&params.iterations().to_le_bytes());
    bytes[8..12].copy_from_slice(&params.parallelism().to_le_bytes());
}

fn read_and_validate_kdf_param_bytes(
    bytes: [u8; KDF_PARAM_BYTES_SIZE],
) -> Result<PasswordKdfParams, Error> {
    let memory_cost_kib = u32::from_le_bytes(bytes[0..4].try_into().expect("4"));
    let iterations = u32::from_le_bytes(bytes[4..8].try_into().expect("4"));
    let parallelism = u32::from_le_bytes(bytes[8..12].try_into().expect("4"));

    if memory_cost_kib > PASSWORD_SEALED_KEY32_MAX_MEMORY_COST_KIB
        || iterations > PASSWORD_SEALED_KEY32_MAX_ITERATIONS
        || parallelism > PASSWORD_KDF_MAX_PARALLELISM
    {
        return Err(Error::PasswordSealedKeyParamsOutOfRange);
    }
    PasswordKdfParams::new(memory_cost_kib, iterations, parallelism)
}
