//! Sortable and pure-random text identifiers.
//!
//! `SortableId` has a byte representation that sorts by creation time. Its
//! text representation is intentionally human-friendly, but it is not sortable.
//!
//! `RandomId` is pure entropy rendered through one of Paranoid's blessed ASCII
//! alphabets.

use std::error::Error as StdError;
use std::fmt;
use std::str::FromStr;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use data_encoding::{BASE32_NOPAD_NOCASE, DecodeKind};

/// Size, in bytes, of a sortable ID.
pub const SORTABLE_ID_SIZE: usize = 16;

/// Length, in bytes, of a sortable ID's text encoding.
pub const SORTABLE_ID_TEXT_LEN: usize = 26;

/// Maximum generated length for a random text ID.
pub const MAX_RANDOM_ID_OUTPUT_LEN: usize = 255;

/// Maximum number of sortable IDs generated by one `new_multi` call.
pub const MAX_SORTABLE_ID_MULTI_COUNT: usize = 255;

const TIME_BYTES: usize = 7;
const RANDOM_BYTES_SIZE: usize = 10;
const TIMESTAMP_BITS: u32 = 52;
const TIMESTAMP_RESOLUTION_MICROS: i64 = 100;
const MAX_TIMESTAMP_TICKS: u64 = (1_u64 << TIMESTAMP_BITS) - 1;
const RANDOM_BUFFER_SIZE: usize = 32;
const BASE32_LOWER_ALPHABET: &[u8; 32] = b"abcdefghijklmnopqrstuvwxyz234567";
const ALPHANUMERIC_LOWERCASE: &[u8] = b"0123456789abcdefghijklmnopqrstuvwxyz";
const ALPHANUMERIC_ANYCASE: &[u8] =
    b"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

/// A 16-byte, byte-sortable timestamped ID.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct SortableId([u8; SORTABLE_ID_SIZE]);

/// A pure-random ASCII text ID.
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct RandomId(String);

/// Error returned by the operating system random source.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RandomError {
    source: getrandom::Error,
}

impl RandomError {
    /// Returns the underlying `getrandom` error.
    pub fn getrandom_error(&self) -> &getrandom::Error {
        &self.source
    }
}

impl fmt::Display for RandomError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.source)
    }
}

impl StdError for RandomError {}

/// Errors returned by ID operations.
#[derive(Debug)]
pub enum Error {
    /// The requested sortable-ID count is too large.
    InvalidSortableIdCount {
        /// The requested ID count.
        actual: usize,
        /// The maximum supported ID count.
        max: usize,
    },
    /// The requested random-ID output length was zero.
    EmptyRandomIdOutputLength,
    /// The requested random-ID output length is too large.
    InvalidRandomIdOutputLength {
        /// The requested output length.
        actual: usize,
        /// The maximum supported output length.
        max: usize,
    },
    /// Raw bytes were not exactly 16 bytes long.
    InvalidIdLength {
        /// The provided byte length.
        actual: usize,
    },
    /// Encoded text was not exactly 26 bytes long.
    InvalidTextLength {
        /// The provided text length.
        actual: usize,
    },
    /// Encoded text contained a non-base32 byte.
    InvalidTextByte {
        /// The byte index where decoding failed.
        index: usize,
        /// The invalid byte at `index`.
        byte: u8,
    },
    /// Secure random byte generation failed.
    Random {
        /// Underlying random-source error.
        source: RandomError,
    },
}

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidSortableIdCount { actual, max } => {
                write!(f, "id: invalid sortable ID count {actual}, max {max}")
            }
            Self::EmptyRandomIdOutputLength => {
                write!(f, "id: random ID output length cannot be zero")
            }
            Self::InvalidRandomIdOutputLength { actual, max } => {
                write!(f, "id: invalid random ID output length {actual}, max {max}")
            }
            Self::InvalidIdLength { actual } => {
                write!(f, "id: invalid ID length {actual}, want {SORTABLE_ID_SIZE}")
            }
            Self::InvalidTextLength { actual } => {
                write!(
                    f,
                    "id: invalid encoded ID length {actual}, want {SORTABLE_ID_TEXT_LEN}"
                )
            }
            Self::InvalidTextByte { index, byte } => {
                write!(f, "id: invalid base32 byte 0x{byte:02x} at index {index}")
            }
            Self::Random { source } => write!(f, "id: random bytes: {source}"),
        }
    }
}

impl StdError for Error {
    fn source(&self) -> Option<&(dyn StdError + 'static)> {
        match self {
            Self::InvalidSortableIdCount { .. }
            | Self::EmptyRandomIdOutputLength
            | Self::InvalidRandomIdOutputLength { .. }
            | Self::InvalidIdLength { .. }
            | Self::InvalidTextLength { .. }
            | Self::InvalidTextByte { .. } => None,
            Self::Random { source } => Some(source),
        }
    }
}

impl From<getrandom::Error> for Error {
    fn from(value: getrandom::Error) -> Self {
        Self::Random {
            source: RandomError { source: value },
        }
    }
}

fn new_id() -> Result<SortableId, Error> {
    new_with_random_fill(fill_with_system_random)
}

fn new_with_random_fill(
    mut fill_random: impl FnMut(&mut [u8]) -> Result<(), Error>,
) -> Result<SortableId, Error> {
    let mut id = SortableId([0_u8; SORTABLE_ID_SIZE]);
    fill_random(&mut id.0[6..])?;
    id.0[6] &= 0x0f;
    put_timestamp_ticks(&mut id.0, unix_micro_to_timestamp_ticks(now_unix_micros()));

    Ok(id)
}

fn new_multi_ids(count: usize) -> Result<Vec<SortableId>, Error> {
    new_multi_with_random_fill(count, fill_with_system_random)
}

fn new_multi_with_random_fill(
    count: usize,
    mut fill_random: impl FnMut(&mut [u8]) -> Result<(), Error>,
) -> Result<Vec<SortableId>, Error> {
    if count > MAX_SORTABLE_ID_MULTI_COUNT {
        return Err(Error::InvalidSortableIdCount {
            actual: count,
            max: MAX_SORTABLE_ID_MULTI_COUNT,
        });
    }

    let mut ids = vec![SortableId([0_u8; SORTABLE_ID_SIZE]); count];
    if count == 0 {
        return Ok(ids);
    }

    let mut random_bytes = vec![0_u8; count * RANDOM_BYTES_SIZE];
    fill_random(&mut random_bytes)?;

    let timestamp_ticks = unix_micro_to_timestamp_ticks(now_unix_micros());
    for (index, id) in ids.iter_mut().enumerate() {
        let offset = index * RANDOM_BYTES_SIZE;
        let random_chunk = &random_bytes[offset..offset + RANDOM_BYTES_SIZE];
        id.0[6] = random_chunk[0] & 0x0f;
        id.0[7..].copy_from_slice(&random_chunk[1..]);
        put_timestamp_ticks(&mut id.0, timestamp_ticks);
    }

    Ok(ids)
}

fn fill_with_system_random(bytes: &mut [u8]) -> Result<(), Error> {
    getrandom::fill(bytes).map_err(Error::from)
}

fn id_to_unix_micros(id: SortableId) -> i64 {
    (read_timestamp_ticks(id.0) as i64) * TIMESTAMP_RESOLUTION_MICROS
}

fn id_to_system_time(id: SortableId) -> SystemTime {
    let unix_micros = id_to_unix_micros(id);
    UNIX_EPOCH + Duration::from_micros(unix_micros as u64)
}

fn serialize_id(id: SortableId) -> String {
    let mut encoded = id.0;
    for index in 0..TIME_BYTES {
        encoded[index] ^= encoded[index + TIME_BYTES];
    }
    encode_base32_no_padding_lower(&encoded)
}

fn parse_id(input: &str) -> Result<SortableId, Error> {
    if input.len() != SORTABLE_ID_TEXT_LEN {
        return Err(Error::InvalidTextLength {
            actual: input.len(),
        });
    }

    let mut bytes = decode_base32_no_padding(input.as_bytes())?;
    for index in 0..TIME_BYTES {
        bytes[index] ^= bytes[index + TIME_BYTES];
    }
    Ok(SortableId(bytes))
}

fn min_id_at_unix_micros(unix_micros: i64) -> SortableId {
    let mut id = [0_u8; SORTABLE_ID_SIZE];
    put_timestamp_ticks(&mut id, unix_micro_to_timestamp_ticks(unix_micros));
    SortableId(id)
}

fn max_id_at_unix_micros(unix_micros: i64) -> SortableId {
    let mut upper = min_id_at_unix_micros(unix_micros);
    upper.0[6] |= 0x0f;
    for byte in &mut upper.0[7..] {
        *byte = 0xff;
    }
    upper
}

impl SortableId {
    /// Generates a new 16-byte sortable ID.
    ///
    /// The leading 52 bits are the current Unix timestamp in
    /// 100-microsecond ticks, and the trailing 76 bits are cryptographically
    /// random.
    pub fn new() -> Result<Self, Error> {
        new_id()
    }

    /// Generates `count` IDs that share one timestamp tick.
    pub fn new_multi(count: usize) -> Result<Vec<Self>, Error> {
        new_multi_ids(count)
    }

    /// Validates and copies raw 16-byte input into a sortable ID.
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, Error> {
        if bytes.len() != SORTABLE_ID_SIZE {
            return Err(Error::InvalidIdLength {
                actual: bytes.len(),
            });
        }

        let mut id = [0_u8; SORTABLE_ID_SIZE];
        id.copy_from_slice(bytes);
        Ok(Self(id))
    }

    /// Returns this ID as raw bytes.
    pub fn as_bytes(&self) -> &[u8; SORTABLE_ID_SIZE] {
        &self.0
    }

    /// Returns this ID as raw bytes by value.
    pub fn into_bytes(self) -> [u8; SORTABLE_ID_SIZE] {
        self.0
    }

    /// Converts this ID to a Unix timestamp in microseconds.
    pub fn to_unix_micros(self) -> i64 {
        id_to_unix_micros(self)
    }

    /// Converts this ID to a `SystemTime` using its encoded timestamp.
    pub fn to_system_time(self) -> SystemTime {
        id_to_system_time(self)
    }

    /// Encodes this ID into its 26-character text form.
    pub fn to_text(self) -> String {
        serialize_id(self)
    }

    /// Decodes an ID from its 26-character base32 text form.
    ///
    /// Both lower-case and upper-case input are accepted.
    pub fn parse(input: &str) -> Result<Self, Error> {
        parse_id(input)
    }

    /// Returns the earliest possible ID for `unix_micros`.
    pub fn min_at_unix_micros(unix_micros: i64) -> Self {
        min_id_at_unix_micros(unix_micros)
    }

    /// Returns the latest possible ID for `unix_micros`.
    pub fn max_at_unix_micros(unix_micros: i64) -> Self {
        max_id_at_unix_micros(unix_micros)
    }
}

impl RandomId {
    /// Generates a random lowercase ASCII alphanumeric ID.
    ///
    /// The returned text contains exactly `output_str_len` ASCII bytes from
    /// `0-9a-z`. Each output byte is sampled without modulo bias.
    pub fn alphanumeric_lowercase(output_str_len: usize) -> Result<Self, Error> {
        random_id_from_alphabet(output_str_len, ALPHANUMERIC_LOWERCASE)
    }

    /// Generates a random ASCII alphanumeric ID using both letter cases.
    ///
    /// The returned text contains exactly `output_str_len` ASCII bytes from
    /// `0-9A-Za-z`. Each output byte is sampled without modulo bias.
    pub fn alphanumeric_anycase(output_str_len: usize) -> Result<Self, Error> {
        random_id_from_alphabet(output_str_len, ALPHANUMERIC_ANYCASE)
    }

    /// Returns the ID text as a string slice.
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Returns the ID text by value.
    pub fn into_string(self) -> String {
        self.0
    }

    /// Returns the byte length of the ID text.
    #[allow(clippy::len_without_is_empty)]
    pub fn len(&self) -> usize {
        self.0.len()
    }
}

impl AsRef<str> for RandomId {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl fmt::Display for RandomId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

fn random_id_from_alphabet(
    output_str_len: usize,
    alphabet: &'static [u8],
) -> Result<RandomId, Error> {
    random_id_from_alphabet_with_random_fill(output_str_len, alphabet, fill_with_system_random)
}

fn random_id_from_alphabet_with_random_fill(
    output_str_len: usize,
    alphabet: &'static [u8],
    mut fill_random: impl FnMut(&mut [u8]) -> Result<(), Error>,
) -> Result<RandomId, Error> {
    if output_str_len == 0 {
        return Err(Error::EmptyRandomIdOutputLength);
    }
    if output_str_len > MAX_RANDOM_ID_OUTPUT_LEN {
        return Err(Error::InvalidRandomIdOutputLength {
            actual: output_str_len,
            max: MAX_RANDOM_ID_OUTPUT_LEN,
        });
    }

    let usable_values = (256 / alphabet.len()) * alphabet.len();
    let mut output = Vec::with_capacity(output_str_len);
    let mut random_buffer = [0_u8; RANDOM_BUFFER_SIZE];
    while output.len() < output_str_len {
        fill_random(&mut random_buffer)?;
        for random_byte in random_buffer {
            let random_value = usize::from(random_byte);
            if random_value >= usable_values {
                continue;
            }
            output.push(alphabet[random_value % alphabet.len()]);
            if output.len() == output_str_len {
                break;
            }
        }
    }

    Ok(RandomId(
        String::from_utf8(output).expect("random ID alphabets are ASCII"),
    ))
}

impl AsRef<[u8]> for SortableId {
    fn as_ref(&self) -> &[u8] {
        &self.0
    }
}

impl fmt::Display for SortableId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.to_text())
    }
}

impl FromStr for SortableId {
    type Err = Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Self::parse(s)
    }
}

fn now_unix_micros() -> i64 {
    match SystemTime::now().duration_since(UNIX_EPOCH) {
        Ok(duration) => duration_to_i64_micros_saturating(duration),
        Err(_) => 0,
    }
}

fn duration_to_i64_micros_saturating(duration: Duration) -> i64 {
    let micros = duration.as_micros();
    if micros > i64::MAX as u128 {
        i64::MAX
    } else {
        micros as i64
    }
}

fn unix_micro_to_timestamp_ticks(unix_micro: i64) -> u64 {
    if unix_micro <= 0 {
        return 0;
    }

    let ticks = (unix_micro / TIMESTAMP_RESOLUTION_MICROS) as u64;
    ticks.min(MAX_TIMESTAMP_TICKS)
}

fn put_timestamp_ticks(id: &mut [u8; SORTABLE_ID_SIZE], ticks: u64) {
    id[0] = (ticks >> 44) as u8;
    id[1] = (ticks >> 36) as u8;
    id[2] = (ticks >> 28) as u8;
    id[3] = (ticks >> 20) as u8;
    id[4] = (ticks >> 12) as u8;
    id[5] = (ticks >> 4) as u8;
    id[6] = (id[6] & 0x0f) | (((ticks & 0x0f) as u8) << 4);
}

fn read_timestamp_ticks(id: [u8; SORTABLE_ID_SIZE]) -> u64 {
    ((id[0] as u64) << 44)
        | ((id[1] as u64) << 36)
        | ((id[2] as u64) << 28)
        | ((id[3] as u64) << 20)
        | ((id[4] as u64) << 12)
        | ((id[5] as u64) << 4)
        | ((id[6] >> 4) as u64)
}

fn encode_base32_no_padding_lower(bytes: &[u8; SORTABLE_ID_SIZE]) -> String {
    let mut output = [0_u8; SORTABLE_ID_TEXT_LEN];
    encode_base32_5_byte_chunk(&bytes[0..5], &mut output[0..8]);
    encode_base32_5_byte_chunk(&bytes[5..10], &mut output[8..16]);
    encode_base32_5_byte_chunk(&bytes[10..15], &mut output[16..24]);
    output[24] = base32_lower(bytes[15] >> 3);
    output[25] = base32_lower((bytes[15] & 0x07) << 2);
    std::str::from_utf8(&output)
        .expect("sortable ID text alphabet is ASCII")
        .to_owned()
}

fn encode_base32_5_byte_chunk(input: &[u8], output: &mut [u8]) {
    debug_assert_eq!(input.len(), 5);
    debug_assert_eq!(output.len(), 8);
    output[0] = base32_lower(input[0] >> 3);
    output[1] = base32_lower(((input[0] & 0x07) << 2) | (input[1] >> 6));
    output[2] = base32_lower((input[1] >> 1) & 0x1f);
    output[3] = base32_lower(((input[1] & 0x01) << 4) | (input[2] >> 4));
    output[4] = base32_lower(((input[2] & 0x0f) << 1) | (input[3] >> 7));
    output[5] = base32_lower((input[3] >> 2) & 0x1f);
    output[6] = base32_lower(((input[3] & 0x03) << 3) | (input[4] >> 5));
    output[7] = base32_lower(input[4] & 0x1f);
}

fn base32_lower(index: u8) -> u8 {
    BASE32_LOWER_ALPHABET[usize::from(index)]
}

fn decode_base32_no_padding(input: &[u8]) -> Result<[u8; SORTABLE_ID_SIZE], Error> {
    let mut output = [0_u8; SORTABLE_ID_SIZE];
    let decoded_len = BASE32_NOPAD_NOCASE
        .decode_mut(input, &mut output)
        .map_err(|partial| {
            let position = partial.error.position;
            match partial.error.kind {
                DecodeKind::Symbol => Error::InvalidTextByte {
                    index: position,
                    byte: input[position],
                },
                DecodeKind::Length => Error::InvalidTextLength {
                    actual: input.len(),
                },
                DecodeKind::Trailing | DecodeKind::Padding => Error::InvalidTextByte {
                    index: position,
                    byte: input[position],
                },
            }
        })?;
    debug_assert_eq!(decoded_len, SORTABLE_ID_SIZE);
    Ok(output)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn assert_lower_base32_text(text: &str) {
        assert_eq!(text.len(), SORTABLE_ID_TEXT_LEN);
        assert!(
            text.bytes()
                .all(|byte| byte.is_ascii_lowercase() || (b'2'..=b'7').contains(&byte)),
            "unexpected id text format: {text:?}"
        );
    }

    #[test]
    fn new_generates_current_timestamped_id() {
        let id = SortableId::new().expect("new id");
        let timestamp = id.to_unix_micros();

        assert!(timestamp > 0);
        assert_eq!(timestamp % TIMESTAMP_RESOLUTION_MICROS, 0);

        let now = now_unix_micros();
        let delta = now - timestamp;
        assert!(
            (-5_000_000..=5_000_000).contains(&delta),
            "timestamp outside expected range: now={now} id={timestamp} delta={delta}"
        );
    }

    #[test]
    fn new_multi_generates_independent_ids_with_shared_timestamp() {
        let ids = SortableId::new_multi(8).expect("ids");
        assert_eq!(ids.len(), 8);

        let expected_timestamp = ids[0].to_unix_micros();
        for id in &ids {
            assert_lower_base32_text(&id.to_text());
            assert_eq!(id.to_unix_micros(), expected_timestamp);
        }

        let mut changed = ids.clone();
        changed[0].0[0] ^= 0xff;
        assert_eq!(changed[1], ids[1]);
    }

    #[test]
    fn new_multi_zero_returns_empty_vec() {
        let ids = SortableId::new_multi(0).expect("ids");
        assert!(ids.is_empty());
    }

    #[test]
    fn new_returns_random_error() {
        let error = new_with_random_fill(|_| Err(Error::from(getrandom::Error::UNSUPPORTED)))
            .expect_err("random failure");

        assert_eq!(
            error.source().expect("getrandom source").to_string(),
            getrandom::Error::UNSUPPORTED.to_string()
        );
    }

    #[test]
    fn new_multi_returns_random_error() {
        let error =
            new_multi_with_random_fill(2, |_| Err(Error::from(getrandom::Error::UNSUPPORTED)))
                .expect_err("random failure");

        assert_eq!(
            error.source().expect("getrandom source").to_string(),
            getrandom::Error::UNSUPPORTED.to_string()
        );
    }

    #[test]
    fn new_multi_rejects_overlarge_counts_before_allocation() {
        assert!(matches!(
            SortableId::new_multi(MAX_SORTABLE_ID_MULTI_COUNT + 1),
            Err(Error::InvalidSortableIdCount {
                actual,
                max: MAX_SORTABLE_ID_MULTI_COUNT,
            }) if actual == MAX_SORTABLE_ID_MULTI_COUNT + 1
        ));
    }

    #[test]
    fn random_error_exposes_getrandom_source() {
        let error = Error::from(getrandom::Error::UNSUPPORTED);
        let source = <Error as StdError>::source(&error).expect("getrandom source");

        assert_eq!(
            source.to_string(),
            getrandom::Error::UNSUPPORTED.to_string()
        );
    }

    #[test]
    fn random_id_lowercase_uses_exact_length_and_lowercase_alphanumeric_alphabet() {
        let id = RandomId::alphanumeric_lowercase(64).expect("random ID");

        assert_eq!(id.len(), 64);
        assert!(
            id.as_str()
                .bytes()
                .all(|byte| byte.is_ascii_digit() || byte.is_ascii_lowercase()),
            "unexpected lowercase random ID text: {id}"
        );
        assert_eq!(id.to_string(), id.as_str());
        assert_eq!(id.as_ref(), id.as_str());
        assert_eq!(id.clone().into_string(), id.as_str());
    }

    #[test]
    fn random_id_anycase_uses_exact_length_and_anycase_alphanumeric_alphabet() {
        let id = RandomId::alphanumeric_anycase(64).expect("random ID");

        assert_eq!(id.len(), 64);
        assert!(
            id.as_str().bytes().all(|byte| byte.is_ascii_alphanumeric()),
            "unexpected anycase random ID text: {id}"
        );
    }

    #[test]
    fn random_id_rejects_zero_length() {
        assert!(matches!(
            RandomId::alphanumeric_lowercase(0),
            Err(Error::EmptyRandomIdOutputLength)
        ));
    }

    #[test]
    fn random_id_rejects_overlarge_output_length() {
        assert!(matches!(
            RandomId::alphanumeric_anycase(MAX_RANDOM_ID_OUTPUT_LEN + 1),
            Err(Error::InvalidRandomIdOutputLength {
                actual,
                max: MAX_RANDOM_ID_OUTPUT_LEN,
            }) if actual == MAX_RANDOM_ID_OUTPUT_LEN + 1
        ));
    }

    #[test]
    fn random_id_generation_returns_random_error() {
        let error = random_id_from_alphabet_with_random_fill(1, ALPHANUMERIC_LOWERCASE, |_| {
            Err(Error::from(getrandom::Error::UNSUPPORTED))
        })
        .expect_err("random failure");

        assert_eq!(
            error.source().expect("getrandom source").to_string(),
            getrandom::Error::UNSUPPORTED.to_string()
        );
    }

    #[test]
    fn random_id_generation_uses_rejection_sampling_without_modulo_bias() {
        let lower = random_id_from_alphabet_with_random_fill(
            3,
            ALPHANUMERIC_LOWERCASE,
            fill_from_bytes([252, 253, 35, 36, 0]),
        )
        .expect("lowercase random ID");
        let anycase = random_id_from_alphabet_with_random_fill(
            3,
            ALPHANUMERIC_ANYCASE,
            fill_from_bytes([248, 249, 61, 62, 0]),
        )
        .expect("anycase random ID");

        assert_eq!(lower.as_str(), "z00");
        assert_eq!(anycase.as_str(), "z00");
    }

    fn fill_from_bytes<const N: usize>(
        bytes: [u8; N],
    ) -> impl FnMut(&mut [u8]) -> Result<(), Error> {
        let mut index = 0;
        move |output| {
            for output_byte in output {
                *output_byte = bytes.get(index).copied().unwrap_or(0);
                index += 1;
            }
            Ok(())
        }
    }

    #[test]
    fn min_id_at_unix_micros_is_byte_sortable() {
        let t0 = 1_738_838_400_123_400_i64;
        let t1 = t0 + TIMESTAMP_RESOLUTION_MICROS;

        let id0 = SortableId::min_at_unix_micros(t0);
        let id1 = SortableId::min_at_unix_micros(t1);

        assert!(id0.as_bytes() < id1.as_bytes());
        assert_eq!(id0.to_unix_micros(), t0);
        assert_eq!(id1.to_unix_micros(), t1);
    }

    #[test]
    fn min_id_at_unix_micros_rounds_down_to_resolution() {
        let id = SortableId::min_at_unix_micros(1_738_838_400_123_456);
        assert_eq!(id.to_unix_micros(), 1_738_838_400_123_400);
    }

    #[test]
    fn min_id_at_unix_micros_clamps_to_supported_range() {
        let max_unix_micro = (MAX_TIMESTAMP_TICKS as i64) * TIMESTAMP_RESOLUTION_MICROS;
        assert_eq!(
            SortableId::min_at_unix_micros(max_unix_micro + TIMESTAMP_RESOLUTION_MICROS * 100)
                .to_unix_micros(),
            max_unix_micro
        );
        assert_eq!(SortableId::min_at_unix_micros(-1).to_unix_micros(), 0);
    }

    #[test]
    fn max_id_at_unix_micros_uses_highest_random_suffix() {
        let lower = SortableId::min_at_unix_micros(1_738_838_400_123_400);
        let upper = SortableId::max_at_unix_micros(1_738_838_400_123_400);

        assert_eq!(lower.to_unix_micros(), upper.to_unix_micros());
        assert!(lower <= upper);
        assert_eq!(upper.as_bytes()[6] & 0x0f, 0x0f);
        assert!(upper.as_bytes()[7..].iter().all(|byte| *byte == 0xff));
    }

    #[test]
    fn min_and_max_id_at_unix_micros_enclose_tick_ids() {
        let lower = SortableId::min_at_unix_micros(1_738_838_400_123_400);
        let upper = SortableId::max_at_unix_micros(1_738_838_400_123_400);

        let mut id = lower;
        id.0[6] |= 0x0a;
        id.0[7] = 0x01;
        id.0[15] = 0xfe;

        assert!(id >= lower);
        assert!(id <= upper);
    }

    #[test]
    fn to_text_has_stable_lower_base32_output() {
        let id = SortableId([
            0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d,
            0x0e, 0x0f,
        ]);

        let first = id.to_text();
        let second = id.to_text();

        assert_eq!(id.0, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]);
        assert_eq!(first, second);
        assert_eq!(first, "a4eqwcipbefqocajbifqydiob4");
        assert_lower_base32_text(&first);
    }

    #[test]
    fn parse_accepts_uppercase_and_lowercase() {
        let id = SortableId([
            0x10, 0x20, 0x30, 0x40, 0x50, 0x60, 0x70, 0x80, 0x90, 0xa0, 0xb0, 0xc0, 0xd0, 0xe0,
            0xf0, 0x11,
        ]);
        let encoded = id.to_text();

        let upper = SortableId::parse(&encoded.to_uppercase()).expect("upper");
        let lower = SortableId::parse(&encoded).expect("lower");

        assert_eq!(upper, lower);
        assert_eq!(lower, id);
    }

    #[test]
    fn parse_rejects_invalid_length() {
        for input in ["", "aa", "a".repeat(SORTABLE_ID_TEXT_LEN - 1).as_str()] {
            assert!(matches!(
                SortableId::parse(input),
                Err(Error::InvalidTextLength { .. })
            ));
        }

        let too_long = "a".repeat(SORTABLE_ID_TEXT_LEN + 1);
        assert!(matches!(
            SortableId::parse(&too_long),
            Err(Error::InvalidTextLength { .. })
        ));
    }

    #[test]
    fn parse_rejects_invalid_characters() {
        let invalid = format!("{}!", "a".repeat(SORTABLE_ID_TEXT_LEN - 1));
        assert!(matches!(
            SortableId::parse(&invalid),
            Err(Error::InvalidTextByte { .. })
        ));
    }

    #[test]
    fn parse_rejects_non_canonical_trailing_bits() {
        let canonical = format!("{}a", "a".repeat(SORTABLE_ID_TEXT_LEN - 1));
        let non_canonical = format!("{}7", "a".repeat(SORTABLE_ID_TEXT_LEN - 1));

        assert_eq!(
            SortableId::parse(&canonical).expect("canonical"),
            SortableId([0_u8; SORTABLE_ID_SIZE])
        );
        assert!(matches!(
            SortableId::parse(&non_canonical),
            Err(Error::InvalidTextByte { .. })
        ));
    }

    #[test]
    fn generated_ids_round_trip_through_text() {
        for _ in 0..256 {
            let id = SortableId::new().expect("new id");
            let encoded = id.to_text();
            assert_lower_base32_text(&encoded);

            let decoded = SortableId::parse(&encoded).expect("parse");
            assert_eq!(decoded, id);
            assert_eq!(decoded.to_text(), encoded);
        }
    }

    #[test]
    fn from_bytes_validates_length_and_copies_input() {
        let mut input = [
            0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d,
            0x0e, 0x0f,
        ];
        let id = SortableId::from_bytes(&input).expect("id");
        assert_eq!(id.as_bytes(), &input);

        input[0] ^= 0xff;
        assert_ne!(id.as_bytes(), &input);

        for bad in [
            &[][..],
            &[1, 2, 3][..],
            &[0; SORTABLE_ID_SIZE - 1][..],
            &[0; SORTABLE_ID_SIZE + 1][..],
        ] {
            assert!(matches!(
                SortableId::from_bytes(bad),
                Err(Error::InvalidIdLength { .. })
            ));
        }
    }

    #[test]
    fn all_zero_id_timestamp_is_zero() {
        assert_eq!(SortableId([0_u8; SORTABLE_ID_SIZE]).to_unix_micros(), 0);
    }

    #[test]
    fn system_time_method_uses_encoded_timestamp() {
        let id = SortableId::min_at_unix_micros(1_738_838_400_123_400);
        assert_eq!(
            id.to_system_time()
                .duration_since(UNIX_EPOCH)
                .expect("post-epoch")
                .as_micros(),
            1_738_838_400_123_400
        );
    }

    #[test]
    fn display_and_from_str_use_text_encoding() {
        let id = SortableId::min_at_unix_micros(1_738_838_400_123_400);
        let text = id.to_string();
        assert_eq!(SortableId::from_str(&text).expect("parse"), id);
    }
}
